/**
 * Writer: generates clean YAML output and creates downloadable ZIP.
 */
import yaml from "js-yaml";
import JSZip from "jszip";
import type { BuiltSpec } from "./builder";

/**
 * Convert a spec object to a clean YAML string.
 */
export function specToYaml(spec: Record<string, unknown>): string {
  return yaml.dump(spec, {
    indent: 2,
    lineWidth: 120,
    noRefs: true,
    sortKeys: false,
    quotingType: '"',
    forceQuotes: false,
  });
}

/**
 * Create a ZIP file containing all built specs as YAML files.
 * Returns a Blob that can be downloaded.
 */
export async function createZip(specs: BuiltSpec[]): Promise<Blob> {
  const zip = new JSZip();

  for (const built of specs) {
    const yamlContent = specToYaml(built.spec);
    zip.file(built.filename, yamlContent);
  }

  // Add a manifest/index file
  const manifest = generateManifest(specs);
  zip.file("_index.yaml", manifest);

  return zip.generateAsync({ type: "blob" });
}

/**
 * Generate a manifest listing all specs and their endpoints.
 */
function generateManifest(specs: BuiltSpec[]): string {
  const entries = specs.map((s) => ({
    file: s.filename,
    title: s.spec.info?.title || s.subsectionId,
    endpoints: s.endpointCount,
  }));

  const manifest = {
    description: "OpenAPI Specification Index - Generated by YAML Fixer",
    totalSpecs: specs.length,
    totalEndpoints: specs.reduce((sum, s) => sum + s.endpointCount, 0),
    specs: entries,
  };

  return yaml.dump(manifest, {
    indent: 2,
    lineWidth: 120,
    noRefs: true,
  });
}
