openapi: 3.0.1
info:
  title: Audit Logs APIs
  description: Audit log retrieval endpoints
  version: 1.0.0
servers:
  - url: https://{host}/v2
    variables:
      host:
        default: eu.api.capillarytech.com
        description: API host
paths:
  /api_gateway/v2/audits:
    get:
      summary: Get audit logs of entities
      description: This page provides you with information on entity audit log API.
      operationId: get-entity-audit-logs
      parameters:
        - name: entityType
          in: query
          description: The type of entity for which you want to fetch audit logs.
          required: true
          schema:
            type: string
            enum:
              - CUSTOMER
              - CARD
        - name: entityId
          in: query
          description: The unique identifier corresponding to the entity.
          required: true
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          description: "The number of results you wish to retrieve. Default value: 10."
          schema:
            type: integer
            format: int32
            default: 10
        - name: pageNo
          in: query
          description: The page number, indicating which page of results to retrieve
          schema:
            type: integer
            format: int32
            default: 0
        - name: sortBy
          in: query
          description: "The field by which results should be sorted. Default value: autoUpdateTime."
          schema:
            type: string
            default: autoUpdateTime
        - name: sortOrder
          in: query
          description: "The order in which results should be sorted. Supported values: ASC, DESC."
          schema:
            type: string
            enum:
              - ASC
              - DESC
        - name: startDate
          in: query
          description: "The start date of the date range. Example: 2022-08-18 16:00:00."
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          description: "The end date of the date range. Example: 2022-08-18 16:00:00."
          schema:
            type: string
            format: date
        - name: referenceType
          in: query
          description: >-
            The reference type. For Extended fields and Custom fields, audit logging is allowed for a maximum of 5
            fields each.
          schema:
            type: string
            enum:
              - Identifier
              - StandardField
              - ExtendedField
              - CustomField
              - CustomerStatus
              - CardStatus
              - SubscriptionStatus
              - CustomerMerge
              - CardCustomField
              - CommChannel
              - CardExtendedField
        - name: referenceValue
          in: query
          description: The value for the selected reference type.
          schema:
            type: string
        - name: includeUserContext
          in: query
          description: Enter true to retrieve user context details.
          schema:
            type: boolean
        - name: source
          in: query
          description: Entity source.
          schema:
            type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Result:
                  value: |-
                    {
                        "data": [
                            {
                                "updatedByUser": null,
                                "updatedBy": 75083604,
                                "orgId": 100458,
                                "entityType": "CUSTOMER",
                                "entityId": 98662653,
                                "createdOn": 1700733054030,
                                "requestId": "25b7780ed479ce80cd95326bcd2a3d91",
                                "till": null,
                                "store": null,
                                "userContextDetails": null,
                                "victimUserDetails": null,
                                "survivorUserDetails": null,
                                "source": "INSTORE",
                                "updatedByMode": "API",
                                "autoUpdateTime": 1700733053872,
                                "events": [
                                    {
                                        "eventType": "Identifiers",
                                        "updatedField": "cardnumber",
                                        "additionalFields": {
                                            "previousValue": "NA",
                                            "currentValue": "DIWALI000000001620232"
                                        },
                                        "associateEntities": null
                                    }
                                ]
                            },
                            {
                                "updatedByUser": null,
                                "updatedBy": 75070896,
                                "orgId": 100458,
                                "entityType": "CUSTOMER",
                                "entityId": 98662653,
                                "createdOn": 1695899825615,
                                "requestId": "2b47b859fa4e0d692b0cac7a200ef9cc",
                                "till": null,
                                "store": null,
                                "userContextDetails": null,
                                "victimUserDetails": null,
                                "survivorUserDetails": null,
                                "source": "INSTORE",
                                "updatedByMode": "API",
                                "autoUpdateTime": 1695899825494,
                                "events": [
                                    {
                                        "eventType": "Identifiers",
                                        "updatedField": "mobile",
                                        "additionalFields": {
                                            "previousValue": "9988776655",
                                            "currentValue": "9986000581"
                                        },
                                        "associateEntities": null
                                    }
                                ]
                            },
                            {
                                "updatedByUser": null,
                                "updatedBy": 75083604,
                                "orgId": 100458,
                                "entityType": "CUSTOMER",
                                "entityId": 98662653,
                                "createdOn": 1689238507261,
                                "requestId": "a272b65e26901f2d2959068543cfb509",
                                "till": null,
                                "store": null,
                                "userContextDetails": null,
                                "victimUserDetails": null,
                                "survivorUserDetails": null,
                                "source": "INSTORE",
                                "updatedByMode": "API",
                                "autoUpdateTime": 1689238507163,
                                "events": [
                                    {
                                        "eventType": "Identifiers",
                                        "updatedField": "mobile",
                                        "additionalFields": {
                                            "previousValue": "9353995291",
                                            "currentValue": "9988776655"
                                        },
                                        "associateEntities": null
                                    }
                                ]
                            },
                            {
                                "updatedByUser": null,
                                "updatedBy": 75083604,
                                "orgId": 100458,
                                "entityType": "CUSTOMER",
                                "entityId": 98662653,
                                "createdOn": 1689238436465,
                                "requestId": "020cf7e0f9827af77f22f6e7833dd0e4",
                                "till": null,
                                "store": null,
                                "userContextDetails": null,
                                "victimUserDetails": null,
                                "survivorUserDetails": null,
                                "source": "INSTORE",
                                "updatedByMode": "API",
                                "autoUpdateTime": 1689238436360,
                                "events": [
                                    {
                                        "eventType": "Identifiers",
                                        "updatedField": "mobile",
                                        "additionalFields": {
                                            "previousValue": "9345644382",
                                            "currentValue": "9353995291"
                                        },
                                        "associateEntities": null
                                    }
                                ]
                            },
                            {
                                "updatedByUser": null,
                                "updatedBy": 75083604,
                                "orgId": 100458,
                                "entityType": "CUSTOMER",
                                "entityId": 98662653,
                                "createdOn": 1688374431078,
                                "requestId": "4bfddb9d-8f0f-4535-8c9e-d72a1922a2f2",
                                "till": null,
                                "store": null,
                                "userContextDetails": null,
                                "victimUserDetails": null,
                                "survivorUserDetails": null,
                                "source": "INSTORE",
                                "updatedByMode": "API",
                                "autoUpdateTime": 1688374430917,
                                "events": [
                                    {
                                        "eventType": "Identifiers",
                                        "updatedField": "cardnumber",
                                        "additionalFields": {
                                            "previousValue": "NA",
                                            "currentValue": "GOLD400000000000011162020"
                                        },
                                        "associateEntities": null
                                    }
                                ]
                            },
                            {
                                "updatedByUser": null,
                                "updatedBy": 75083604,
                                "orgId": 100458,
                                "entityType": "CUSTOMER",
                                "entityId": 98662653,
                                "createdOn": 1687954900362,
                                "requestId": "91a3cfc4b2bbcb9426bbfb51966b6549",
                                "till": null,
                                "store": null,
                                "userContextDetails": null,
                                "victimUserDetails": null,
                                "survivorUserDetails": null,
                                "source": "INSTORE",
                                "updatedByMode": "API",
                                "autoUpdateTime": 1687954900155,
                                "events": [
                                    {
                                        "eventType": "Identifiers",
                                        "updatedField": "cardnumber",
                                        "additionalFields": {
                                            "previousValue": "NA",
                                            "currentValue": "BUK0000044849PR"
                                        },
                                        "associateEntities": null
                                    }
                                ]
                            },
                            {
                                "updatedByUser": null,
                                "updatedBy": 75036445,
                                "orgId": 100458,
                                "entityType": "CUSTOMER",
                                "entityId": 98662653,
                                "createdOn": 1670992526580,
                                "requestId": "2e8a8897bc351889b17d45b6d10feec5",
                                "till": null,
                                "store": null,
                                "userContextDetails": null,
                                "victimUserDetails": null,
                                "survivorUserDetails": null,
                                "source": "INSTORE",
                                "updatedByMode": "API",
                                "autoUpdateTime": 1670992526552,
                                "events": [
                                    {
                                        "eventType": "Identifiers",
                                        "updatedField": "email",
                                        "additionalFields": {
                                            "previousValue": "NA",
                                            "currentValue": "user@example.com"
                                        },
                                        "associateEntities": null
                                    }
                                ]
                            }
                        ],
                        "pagination": {
                            "totalElements": 7,
                            "totalPages": 1,
                            "numberOfElements": 7,
                            "number": 0
                        }
                    }
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        updatedByUser: {}
                        updatedBy:
                          type: integer
                          example: 75083604
                          default: 0
                        orgId:
                          type: integer
                          example: 100458
                          default: 0
                        entityType:
                          type: string
                          example: CUSTOMER
                        entityId:
                          type: integer
                          example: 98662653
                          default: 0
                        createdOn:
                          type: integer
                          example: 1700733054030
                          default: 0
                        requestId:
                          type: string
                          example: 25b7780ed479ce80cd95326bcd2a3d91
                        till: {}
                        store: {}
                        userContextDetails: {}
                        victimUserDetails: {}
                        survivorUserDetails: {}
                        source:
                          type: string
                          example: INSTORE
                        updatedByMode:
                          type: string
                          example: API
                        autoUpdateTime:
                          type: integer
                          example: 1700733053872
                          default: 0
                        events:
                          type: array
                          items:
                            type: object
                            properties:
                              eventType:
                                type: string
                                example: Identifiers
                              updatedField:
                                type: string
                                example: cardnumber
                              additionalFields:
                                type: object
                                properties:
                                  previousValue:
                                    type: string
                                    example: NA
                                  currentValue:
                                    type: string
                                    example: DIWALI000000001620232
                              associateEntities: {}
                  pagination:
                    type: object
                    properties:
                      totalElements:
                        type: integer
                        example: 7
                        default: 0
                      totalPages:
                        type: integer
                        example: 1
                        default: 0
                      numberOfElements:
                        type: integer
                        example: 7
                        default: 0
                      number:
                        type: integer
                        example: 0
                        default: 0
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
    oauthToken:
      type: apiKey
      in: header
      name: X-CAP-API-OAUTH-TOKEN
security:
  - basicAuth: []
