openapi: 3.0.1
info:
  title: Customer (V2 Lookup) APIs
  description: Customer lookup endpoints - Version 2
  version: 1.0.0
servers:
  - url: https://{host}/v2
    variables:
      host:
        default: eu.api.capillarytech.com
        description: API host
paths:
  /v2.1/customers/lookup/promotionData:
    get:
      summary: Get Loyalty Promotion List of a Customer (Connected Org)
      operationId: connectedorgs-get-promotion-list-for-a-customer
      parameters:
        - name: identifierName
          in: query
          description: Identifier type to identify the customer.
          required: true
          schema:
            type: string
        - name: identifierValue
          in: query
          description: Value of the identifier.
          required: true
          schema:
            type: string
        - name: source
          in: query
          description: Specifies the source from where customer details are retrieved.
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: Number of results that need to be displayed. The values from zero to a maximum of 100 are supported.
          schema:
            type: string
        - name: offset
          in: query
          description: Start index for data retrieval. This value should not be negative.
          schema:
            type: string
        - name: DATA-SCOPE-ORG
          in: header
          description: List of Organisation IDs
          schema:
            type: string
        - name: DATA-SCOPE
          in: header
          description: The scope to authorize access (SELF, OTHER, ALL)
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Result:
                  value: |-
                    {
                        "pageDetails": {
                            "pageNumber": 0,
                            "pageSize": 10,
                            "totalEntries": 1,
                            "pageCount": 1
                        },
                        "customerId": 347297848,
                        "promotions": [
                            {
                                "promotionId": 1122938,
                                "promotionName": "Award50",
                                "programId": 1147,
                                "startDate": "2024-08-30T00:00:00.000Z",
                                "endDate": "2024-09-29T23:59:59.000Z",
                                "identifier": "ed64e808-dc10-4784-a752-eb7d8d55c87e",
                                "description": "Award 50",
                                "active": true,
                                "eventName": "TransactionAdd",
                                "limits": {
                                    "maxPointsPerEvent": "0",
                                    "pointsPerCustomer": "0",
                                    "numberOFTimesPerCustomer": 0,
                                    "totalPointsInPromotion": "0"
                                },
                                "customerUsage": {
                                    "currentPointsPerCustomer": "50.000",
                                    "currentNumberOfTimesPerCustomer": 1,
                                    "currentTotalPointsInPromotion": "0"
                                },
                                "pointsOfferType": "GENERIC",
                                "promotionRestriction": {
                                    "issualRestrictions": [],
                                    "earnRestrictions": [],
                                    "redemptionRestrictions": []
                                },
                                "orgId": 50405
                            }
                        ],
                        "warnings": []
                    }
              schema:
                type: object
                properties:
                  pageDetails:
                    type: object
                    properties:
                      pageNumber:
                        type: integer
                        example: 0
                        default: 0
                      pageSize:
                        type: integer
                        example: 10
                        default: 0
                      totalEntries:
                        type: integer
                        example: 1
                        default: 0
                      pageCount:
                        type: integer
                        example: 1
                        default: 0
                  customerId:
                    type: integer
                    example: 347297848
                    default: 0
                  promotions:
                    type: array
                    items:
                      type: object
                      properties:
                        promotionId:
                          type: integer
                          example: 1122938
                          default: 0
                        promotionName:
                          type: string
                          example: Award50
                        programId:
                          type: integer
                          example: 1147
                          default: 0
                        startDate:
                          type: string
                          example: "2024-08-30T00:00:00.000Z"
                        endDate:
                          type: string
                          example: "2024-09-29T23:59:59.000Z"
                        identifier:
                          type: string
                          example: ed64e808-dc10-4784-a752-eb7d8d55c87e
                        description:
                          type: string
                          example: Award 50
                        active:
                          type: boolean
                          example: true
                          default: true
                        eventName:
                          type: string
                          example: TransactionAdd
                        limits:
                          type: object
                          properties:
                            maxPointsPerEvent:
                              type: string
                              example: "0"
                            pointsPerCustomer:
                              type: string
                              example: "0"
                            numberOFTimesPerCustomer:
                              type: integer
                              example: 0
                              default: 0
                            totalPointsInPromotion:
                              type: string
                              example: "0"
                        customerUsage:
                          type: object
                          properties:
                            currentPointsPerCustomer:
                              type: string
                              example: "50.000"
                            currentNumberOfTimesPerCustomer:
                              type: integer
                              example: 1
                              default: 0
                            currentTotalPointsInPromotion:
                              type: string
                              example: "0"
                        pointsOfferType:
                          type: string
                          example: GENERIC
                        promotionRestriction:
                          type: object
                          properties:
                            issualRestrictions:
                              type: array
                            earnRestrictions:
                              type: array
                            redemptionRestrictions:
                              type: array
                        orgId:
                          type: integer
                          example: 50405
                          default: 0
                  warnings:
                    type: array
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: |-
                    {
                        "errors": [
                            {
                                "status": false,
                                "message": "Invalid source",
                                "code": 8003
                            }
                    }      
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
    oauthToken:
      type: apiKey
      in: header
      name: X-CAP-API-OAUTH-TOKEN
security:
  - basicAuth: []
