openapi: 3.0.1
info:
  title: Rich Text Content for Rewards APIs
  description: Rich text content metadata management for rewards
  version: 1.0.0
servers:
  - url: https://{host}/v1
    variables:
      host:
        default: eu.api.capillarytech.com
        description: API host
paths:
  /api_gateway/rewards/core/v1/brand/richContentMeta:
    get:
      summary: Get all Rich Text Content Metadata for specific brand
      description: This API is used to fetch rich content metadata for rewards within a brand.
      operationId: get-all-rich-text-content-metadata-for-brand
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Result:
                  value: |-
                    {
                        "richContentMetaROS": [
                            {
                                "id": 4,
                                "name": "RCtest22",
                                "description": "RC1_desc",
                                "isMandatory": false,
                                "isActive": true,
                                "scope": "REWARD",
                                "defaultValue": null,
                                "createdBy": 75161973,
                                "createdOn": 1742256000000,
                                "lastUpdatedBy": 75161973,
                                "lastUpdatedOn": 1742342400000
                            },
                            {
                                "id": 5,
                                "name": "RCtest2",
                                "description": "RC2_desc",
                                "isMandatory": true,
                                "isActive": true,
                                "scope": "REWARD",
                                "defaultValue": "en",
                                "createdBy": 75161973,
                                "createdOn": 1742342400000,
                                "lastUpdatedBy": 75161973,
                                "lastUpdatedOn": 1742342400000
                            },
                            {
                                "id": 2,
                                "name": "RC3",
                                "description": "RC1_desc",
                                "isMandatory": false,
                                "isActive": true,
                                "scope": "REWARD",
                                "defaultValue": null,
                                "createdBy": 75161973,
                                "createdOn": 1742256000000,
                                "lastUpdatedBy": 75161973,
                                "lastUpdatedOn": 1742256000000
                            },
                            {
                                "id": 3,
                                "name": "RC2",
                                "description": "RC1_desc",
                                "isMandatory": false,
                                "isActive": true,
                                "scope": "REWARD",
                                "defaultValue": null,
                                "createdBy": 75161973,
                                "createdOn": 1742256000000,
                                "lastUpdatedBy": 75161973,
                                "lastUpdatedOn": 1742256000000
                            },
                            {
                                "id": 1,
                                "name": "RC345",
                                "description": "RC2_desc",
                                "isMandatory": true,
                                "isActive": true,
                                "scope": "REWARD",
                                "defaultValue": "en",
                                "createdBy": 75161973,
                                "createdOn": 1742256000000,
                                "lastUpdatedBy": 75161973,
                                "lastUpdatedOn": 1742256000000
                            }
                        ],
                        "pagingDto": {
                            "last": true,
                            "totalElements": 5,
                            "totalPages": 1,
                            "numberOfElements": 5,
                            "first": true,
                            "size": 10,
                            "number": 0
                        }
                    }
              schema:
                type: object
                properties:
                  richContentMetaROS:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 4
                          default: 0
                        name:
                          type: string
                          example: RCtest22
                        description:
                          type: string
                          example: RC1_desc
                        isMandatory:
                          type: boolean
                          example: false
                          default: true
                        isActive:
                          type: boolean
                          example: true
                          default: true
                        scope:
                          type: string
                          example: REWARD
                        defaultValue: {}
                        createdBy:
                          type: integer
                          example: 75161973
                          default: 0
                        createdOn:
                          type: integer
                          example: 1742256000000
                          default: 0
                        lastUpdatedBy:
                          type: integer
                          example: 75161973
                          default: 0
                        lastUpdatedOn:
                          type: integer
                          example: 1742342400000
                          default: 0
                  pagingDto:
                    type: object
                    properties:
                      last:
                        type: boolean
                        example: true
                        default: true
                      totalElements:
                        type: integer
                        example: 5
                        default: 0
                      totalPages:
                        type: integer
                        example: 1
                        default: 0
                      numberOfElements:
                        type: integer
                        example: 5
                        default: 0
                      first:
                        type: boolean
                        example: true
                        default: true
                      size:
                        type: integer
                        example: 10
                        default: 0
                      number:
                        type: integer
                        example: 0
                        default: 0
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
    post:
      summary: Create Rich Text Content Metadata for Rewards
      operationId: create-rich-content-meta
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Result:
                  value: |-
                    {
                        "id": 6,
                        "name": "RCtest",
                        "description": "RC2_desc",
                        "isMandatory": true,
                        "isActive": false,
                        "scope": "REWARD",
                        "defaultValue": "en",
                        "createdBy": 75161973,
                        "createdOn": 1743258861441,
                        "lastUpdatedBy": 75161973,
                        "lastUpdatedOn": 1743258861441
                    }
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 6
                    default: 0
                  name:
                    type: string
                    example: RCtest
                  description:
                    type: string
                    example: RC2_desc
                  isMandatory:
                    type: boolean
                    example: true
                    default: true
                  isActive:
                    type: boolean
                    example: false
                    default: true
                  scope:
                    type: string
                    example: REWARD
                  defaultValue:
                    type: string
                    example: en
                  createdBy:
                    type: integer
                    example: 75161973
                    default: 0
                  createdOn:
                    type: integer
                    example: 1743258861441
                    default: 0
                  lastUpdatedBy:
                    type: integer
                    example: 75161973
                    default: 0
                  lastUpdatedOn:
                    type: integer
                    example: 1743258861441
                    default: 0
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
  /api_gateway/rewards/core/v1/brand/richContentMeta/{RichcontentmetaID}:
    put:
      summary: Update Rich Text Content Metadata for Rewards
      operationId: update-rich-content
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Result:
                  value: |-
                    {
                        "id": 10,
                        "name": "RCtestwithdefaultvalue",
                        "description": "RC2_desc",
                        "isMandatory": false,
                        "isActive": false,
                        "scope": "REWARD",
                        "defaultValue": "hello this is your reward",
                        "createdBy": 75161973,
                        "createdOn": 1743270626236,
                        "lastUpdatedBy": 75161973,
                        "lastUpdatedOn": 1743270626236
                    }
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 10
                    default: 0
                  name:
                    type: string
                    example: RCtestwithdefaultvalue
                  description:
                    type: string
                    example: RC2_desc
                  isMandatory:
                    type: boolean
                    example: false
                    default: true
                  isActive:
                    type: boolean
                    example: false
                    default: true
                  scope:
                    type: string
                    example: REWARD
                  defaultValue:
                    type: string
                    example: hello this is your reward
                  createdBy:
                    type: integer
                    example: 75161973
                    default: 0
                  createdOn:
                    type: integer
                    example: 1743270626236
                    default: 0
                  lastUpdatedBy:
                    type: integer
                    example: 75161973
                    default: 0
                  lastUpdatedOn:
                    type: integer
                    example: 1743270626236
                    default: 0
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
    oauthToken:
      type: apiKey
      in: header
      name: X-CAP-API-OAUTH-TOKEN
security:
  - basicAuth: []
