openapi: 3.0.1
info:
  title: Reward Catalog Categories APIs
  description: Reward category management endpoints
  version: 1.0.0
servers:
  - url: https://{host}/v1
    variables:
      host:
        default: eu.api.capillarytech.com
        description: API host
paths:
  /api_gateway/rewards/core/v1/metadata/category/create:
    post:
      summary: Create Reward Category
      description: Create a new reward category.
      operationId: create-reward-category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - brandId
                - name
              properties:
                brandId:
                  type: integer
                  description: Unique identifier for the brand.
                  format: int64
                name:
                  type: string
                  description: Name of the reward category to be created.
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Sample Response:
                  value: |-
                    {
                        "status": {
                            "success": true,
                            "code": 2002,
                            "message": "Category save successfully"
                        },
                        "category": {
                            "id": 129,
                            "name": "general",
                            "enabled": true
                        }
                    }
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                        default: true
                      code:
                        type: integer
                        example: 2002
                        default: 0
                      message:
                        type: string
                        example: Category save successfully
                  category:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 129
                        default: 0
                      name:
                        type: string
                        example: general
                      enabled:
                        type: boolean
                        example: true
                        default: true
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
  /api_gateway/rewards/core/v1/metadata/category/{categoryId}/status/{action}/brand/{brandId}:
    put:
      summary: Enable or Disable Reward Categories
      description: Enable or disable a particular reward category.
      operationId: enable-or-disable-reward-categories
      parameters:
        - name: categoryId
          in: path
          description: Unique identifier for the reward category that needs to be enabled.
          schema:
            type: integer
            format: int32
          required: true
        - name: brandId
          in: path
          description: Unique identifier for the brand under which the reward category is associated.
          schema:
            type: integer
            format: int64
          required: true
        - name: action
          in: path
          description: Action to be performed.
          schema:
            type: string
            enum:
              - enable
              - disable
          required: true
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Sample Response:
                  value: |-
                    {
                        "status": {
                            "success": true,
                            "code": 2006,
                            "message": "Category updated successfully"
                        }
                    }
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                        default: true
                      code:
                        type: integer
                        example: 2006
                        default: 0
                      message:
                        type: string
                        example: Category updated successfully
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
  /api_gateway/rewards/core/v1/metadata/categories/brand/{brandId}:
    get:
      summary: Get Reward Category
      description: Get reward categories for a particluar brand.
      operationId: get-reward-category
      parameters:
        - name: brandId
          in: path
          description: Unique identifier for the brand.
          schema:
            type: integer
            format: int64
          required: true
        - name: brand name
          in: path
          description: Name of the brand for which you want to retrieve the reward categories.
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Result:
                  value: |-
                    {
                        "status": {
                            "success": true,
                            "code": 200,
                            "message": "Category fetched successfully"
                        },
                        "categoryList": [
                            {
                                "id": 128,
                                "name": "tickets",
                                "enabled": false
                            },
                            {
                                "id": 111,
                                "name": "training",
                                "enabled": true
                            }
                        ]
                    }
                Invalid brandId:
                  value: |-
                    {
                        "status": {
                            "success": false,
                            "code": 3004,
                            "message": "Brand not found"
                        },
                        "categoryList": null
                    }
                With sortBy=lastUpdatedOn:
                  value: |-
                    {
                        "status": {
                            "success": true,
                            "code": 200,
                            "message": "Category fetched successfully"
                        },
                        "categoryList": [
                            {
                                "id": 170,
                                "name": "toys",
                                "enabled": true,
                                "createdOn": 1735816377000,
                                "lastUpdatedOn": 1735816377000,
                                "createdBy": null,
                                "lastUpdatedBy": null,
                                "createdOnDateTime": "2025-01-02T11:12:57Z",
                                "lastUpdatedOnDateTime": "2025-01-02T11:12:57Z"
                            },
                            {
                                "id": 229,
                                "name": "joreward",
                                "enabled": true,
                                "createdOn": 1741059743000,
                                "lastUpdatedOn": 1741059743000,
                                "createdBy": null,
                                "lastUpdatedBy": null,
                                "createdOnDateTime": "2025-03-04T03:42:23Z",
                                "lastUpdatedOnDateTime": "2025-03-04T03:42:23Z"
                            },
                            {
                                "id": 251,
                                "name": "docdemo",
                                "enabled": true,
                                "createdOn": 1742387687000,
                                "lastUpdatedOn": 1742387687000,
                                "createdBy": null,
                                "lastUpdatedBy": null,
                                "createdOnDateTime": "2025-03-19T12:34:47Z",
                                "lastUpdatedOnDateTime": "2025-03-19T12:34:47Z"
                            }
                        ]
                    }
              schema:
                oneOf:
                  - type: object
                    properties:
                      status:
                        type: object
                        properties:
                          success:
                            type: boolean
                            example: true
                            default: true
                          code:
                            type: integer
                            example: 200
                            default: 0
                          message:
                            type: string
                            example: Category fetched successfully
                      categoryList:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 128
                              default: 0
                            name:
                              type: string
                              example: tickets
                            enabled:
                              type: boolean
                              example: false
                              default: true
                  - title: Invalid brandId
                    type: object
                    properties:
                      status:
                        type: object
                        properties:
                          success:
                            type: boolean
                            example: false
                            default: true
                          code:
                            type: integer
                            example: 3004
                            default: 0
                          message:
                            type: string
                            example: Brand not found
                      categoryList: {}
                  - title: With sortBy=lastUpdatedOn
                    type: object
                    properties:
                      status:
                        type: object
                        properties:
                          success:
                            type: boolean
                            example: true
                            default: true
                          code:
                            type: integer
                            example: 200
                            default: 0
                          message:
                            type: string
                            example: Category fetched successfully
                      categoryList:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 170
                              default: 0
                            name:
                              type: string
                              example: toys
                            enabled:
                              type: boolean
                              example: true
                              default: true
                            createdOn:
                              type: integer
                              example: 1735816377000
                              default: 0
                            lastUpdatedOn:
                              type: integer
                              example: 1735816377000
                              default: 0
                            createdBy: {}
                            lastUpdatedBy: {}
                            createdOnDateTime:
                              type: string
                              example: "2025-01-02T11:12:57Z"
                            lastUpdatedOnDateTime:
                              type: string
                              example: "2025-01-02T11:12:57Z"
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
    oauthToken:
      type: apiKey
      in: header
      name: X-CAP-API-OAUTH-TOKEN
security:
  - basicAuth: []
