openapi: 3.0.1
info:
  title: File Service APIs
  description: Image upload endpoints for rewards
  version: 1.0.0
servers:
  - url: https://{host}/v1
    variables:
      host:
        default: eu.api.capillarytech.com
        description: API host
paths:
  /api_gateway/file-service/rewards/{file name with extension}:
    post:
      summary: Upload images to file service
      operationId: post-images-to-file-service
      parameters:
        - name: fileName
          in: path
          description: Name of the image to upload with extension.
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Result:
                  value: |-
                    {
                        "code": 200,
                        "status": "true",
                        "message": "Successfully uploaded file",
                        "file": {
                            "name": "test.png",
                            "namespace": "rewards",
                            "version": 2,
                            "acl": "PRIVATE",
                            "fileSize": "51",
                            "file_handle": "73e78929-1e07-4cc5-a738-b54470a7dc8c",
                            "content_type": "image/png",
                            "s3_token": "rewards/100606/b21f3aea-ad38-4634-82a4-db2aaa0b.png",
                            "latest_version": 2,
                            "last_modified": "2024-05-08 09:10:59",
                            "s3_url": "s3://eucrm-solutions/rewards/100606/b21f3aea-ad38-4634-82a4-db2aaa0b.png"
                        },
                        "secureFilePath": "https://eucrm-solutions.s3-eu-west-1.amazonaws.com/rewards/100606/b21f3aea-ad38-4634-82a4-db2aaa0b.png?X-Amz-Security-Token=FwoGZXIvYXdzEJ3%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDPltNW6lwqLl1xXlfyLIAaxPIuF7uCnnmqOoXU72eVlsn0Lut7GRbf7kme0GYrC8dqLV4UeWGGwizdrjT2QcANwqoAJRYQDvHYHndQuRt8Rvs3%2B%2BaXtUaW6YYekA65tkH%2BeSg2YaEoTRGuep7rOxHGSmpCaxJ767Za3vi6B3CpeYh5U1LZOeJHS5v3uLCdTHleIj8mutjwoX1OuWlPxEwxAtOOABU7ISXrJxTwVfMWANzfuxNyN2jR0kKpRNHq%2FozXEsVuw2owTyr9VK6wwCeMS5MDVZjANIKI7k67EGMi0%2F6Je5Y9Alnn8IgGBzdYmeEub7mDk1%2FBzhZwySJ4O1osP2n6iWFi%2FEyeaPeco%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240508T034059Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIAXKEP2EMBVBC5UMM3%2F20240508%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Signature=86c114267239ef985ff81c32ad0fa1d6b0618c70e42c2a74217ea1e5d6eec1a8"
                    }
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                    default: 0
                  status:
                    type: string
                    example: "true"
                  message:
                    type: string
                    example: Successfully uploaded file
                  file:
                    type: object
                    properties:
                      name:
                        type: string
                        example: test.png
                      namespace:
                        type: string
                        example: rewards
                      version:
                        type: integer
                        example: 2
                        default: 0
                      acl:
                        type: string
                        example: PRIVATE
                      fileSize:
                        type: string
                        example: "51"
                      file_handle:
                        type: string
                        example: 73e78929-1e07-4cc5-a738-b54470a7dc8c
                      content_type:
                        type: string
                        example: image/png
                      s3_token:
                        type: string
                        example: rewards/100606/b21f3aea-ad38-4634-82a4-db2aaa0b.png
                      latest_version:
                        type: integer
                        example: 2
                        default: 0
                      last_modified:
                        type: string
                        example: "2024-05-08 09:10:59"
                      s3_url:
                        type: string
                        example: s3://eucrm-solutions/rewards/100606/b21f3aea-ad38-4634-82a4-db2aaa0b.png
                  secureFilePath:
                    type: string
                    example: >-
                      https://eucrm-solutions.s3-eu-west-1.amazonaws.com/rewards/100606/b21f3aea-ad38-4634-82a4-db2aaa0b.png?X-Amz-Security-Token=FwoGZXIvYXdzEJ3%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDPltNW6lwqLl1xXlfyLIAaxPIuF7uCnnmqOoXU72eVlsn0Lut7GRbf7kme0GYrC8dqLV4UeWGGwizdrjT2QcANwqoAJRYQDvHYHndQuRt8Rvs3%2B%2BaXtUaW6YYekA65tkH%2BeSg2YaEoTRGuep7rOxHGSmpCaxJ767Za3vi6B3CpeYh5U1LZOeJHS5v3uLCdTHleIj8mutjwoX1OuWlPxEwxAtOOABU7ISXrJxTwVfMWANzfuxNyN2jR0kKpRNHq%2FozXEsVuw2owTyr9VK6wwCeMS5MDVZjANIKI7k67EGMi0%2F6Je5Y9Alnn8IgGBzdYmeEub7mDk1%2FBzhZwySJ4O1osP2n6iWFi%2FEyeaPeco%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240508T034059Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIAXKEP2EMBVBC5UMM3%2F20240508%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Signature=86c114267239ef985ff81c32ad0fa1d6b0618c70e42c2a74217ea1e5d6eec1a8
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
    oauthToken:
      type: apiKey
      in: header
      name: X-CAP-API-OAUTH-TOKEN
security:
  - basicAuth: []
